version: '3.8'

services:
  url_shortener_test:
    image: postgres:17-alpine
    container_name: url_shortener_test
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${PG_NAME}
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
    ports:
      - "${PG_PORT_TESTS}:5432"
