// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/egor200512/URL_shortener/services/analytics/internal/models"
	mock "github.com/stretchr/testify/mock"
)

// NewIAnalyticsRepo creates a new instance of IAnalyticsRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIAnalyticsRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *IAnalyticsRepo {
	mock := &IAnalyticsRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// IAnalyticsRepo is an autogenerated mock type for the IAnalyticsRepo type
type IAnalyticsRepo struct {
	mock.Mock
}

type IAnalyticsRepo_Expecter struct {
	mock *mock.Mock
}

func (_m *IAnalyticsRepo) EXPECT() *IAnalyticsRepo_Expecter {
	return &IAnalyticsRepo_Expecter{mock: &_m.Mock}
}

// GetEvents provides a mock function for the type IAnalyticsRepo
func (_mock *IAnalyticsRepo) GetEvents(ctx context.Context, limit int32, offset int32) ([]*models.LinkEvent, int32, error) {
	ret := _mock.Called(ctx, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for GetEvents")
	}

	var r0 []*models.LinkEvent
	var r1 int32
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int32, int32) ([]*models.LinkEvent, int32, error)); ok {
		return returnFunc(ctx, limit, offset)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int32, int32) []*models.LinkEvent); ok {
		r0 = returnFunc(ctx, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.LinkEvent)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int32, int32) int32); ok {
		r1 = returnFunc(ctx, limit, offset)
	} else {
		r1 = ret.Get(1).(int32)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, int32, int32) error); ok {
		r2 = returnFunc(ctx, limit, offset)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// IAnalyticsRepo_GetEvents_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetEvents'
type IAnalyticsRepo_GetEvents_Call struct {
	*mock.Call
}

// GetEvents is a helper method to define mock.On call
//   - ctx context.Context
//   - limit int32
//   - offset int32
func (_e *IAnalyticsRepo_Expecter) GetEvents(ctx interface{}, limit interface{}, offset interface{}) *IAnalyticsRepo_GetEvents_Call {
	return &IAnalyticsRepo_GetEvents_Call{Call: _e.mock.On("GetEvents", ctx, limit, offset)}
}

func (_c *IAnalyticsRepo_GetEvents_Call) Run(run func(ctx context.Context, limit int32, offset int32)) *IAnalyticsRepo_GetEvents_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int32
		if args[1] != nil {
			arg1 = args[1].(int32)
		}
		var arg2 int32
		if args[2] != nil {
			arg2 = args[2].(int32)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *IAnalyticsRepo_GetEvents_Call) Return(linkEvents []*models.LinkEvent, n int32, err error) *IAnalyticsRepo_GetEvents_Call {
	_c.Call.Return(linkEvents, n, err)
	return _c
}

func (_c *IAnalyticsRepo_GetEvents_Call) RunAndReturn(run func(ctx context.Context, limit int32, offset int32) ([]*models.LinkEvent, int32, error)) *IAnalyticsRepo_GetEvents_Call {
	_c.Call.Return(run)
	return _c
}

// GetLinkStats provides a mock function for the type IAnalyticsRepo
func (_mock *IAnalyticsRepo) GetLinkStats(ctx context.Context, shortLink string) (*models.LinkStats, error) {
	ret := _mock.Called(ctx, shortLink)

	if len(ret) == 0 {
		panic("no return value specified for GetLinkStats")
	}

	var r0 *models.LinkStats
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*models.LinkStats, error)); ok {
		return returnFunc(ctx, shortLink)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *models.LinkStats); ok {
		r0 = returnFunc(ctx, shortLink)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.LinkStats)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, shortLink)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// IAnalyticsRepo_GetLinkStats_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetLinkStats'
type IAnalyticsRepo_GetLinkStats_Call struct {
	*mock.Call
}

// GetLinkStats is a helper method to define mock.On call
//   - ctx context.Context
//   - shortLink string
func (_e *IAnalyticsRepo_Expecter) GetLinkStats(ctx interface{}, shortLink interface{}) *IAnalyticsRepo_GetLinkStats_Call {
	return &IAnalyticsRepo_GetLinkStats_Call{Call: _e.mock.On("GetLinkStats", ctx, shortLink)}
}

func (_c *IAnalyticsRepo_GetLinkStats_Call) Run(run func(ctx context.Context, shortLink string)) *IAnalyticsRepo_GetLinkStats_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *IAnalyticsRepo_GetLinkStats_Call) Return(linkStats *models.LinkStats, err error) *IAnalyticsRepo_GetLinkStats_Call {
	_c.Call.Return(linkStats, err)
	return _c
}

func (_c *IAnalyticsRepo_GetLinkStats_Call) RunAndReturn(run func(ctx context.Context, shortLink string) (*models.LinkStats, error)) *IAnalyticsRepo_GetLinkStats_Call {
	_c.Call.Return(run)
	return _c
}

// InsertEvent provides a mock function for the type IAnalyticsRepo
func (_mock *IAnalyticsRepo) InsertEvent(ctx context.Context, event *models.LinkEvent) error {
	ret := _mock.Called(ctx, event)

	if len(ret) == 0 {
		panic("no return value specified for InsertEvent")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *models.LinkEvent) error); ok {
		r0 = returnFunc(ctx, event)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// IAnalyticsRepo_InsertEvent_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InsertEvent'
type IAnalyticsRepo_InsertEvent_Call struct {
	*mock.Call
}

// InsertEvent is a helper method to define mock.On call
//   - ctx context.Context
//   - event *models.LinkEvent
func (_e *IAnalyticsRepo_Expecter) InsertEvent(ctx interface{}, event interface{}) *IAnalyticsRepo_InsertEvent_Call {
	return &IAnalyticsRepo_InsertEvent_Call{Call: _e.mock.On("InsertEvent", ctx, event)}
}

func (_c *IAnalyticsRepo_InsertEvent_Call) Run(run func(ctx context.Context, event *models.LinkEvent)) *IAnalyticsRepo_InsertEvent_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *models.LinkEvent
		if args[1] != nil {
			arg1 = args[1].(*models.LinkEvent)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *IAnalyticsRepo_InsertEvent_Call) Return(err error) *IAnalyticsRepo_InsertEvent_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *IAnalyticsRepo_InsertEvent_Call) RunAndReturn(run func(ctx context.Context, event *models.LinkEvent) error) *IAnalyticsRepo_InsertEvent_Call {
	_c.Call.Return(run)
	return _c
}
