// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/egor200512/URL_shortener/shared/gen/analytics"
	mock "github.com/stretchr/testify/mock"
)

// NewIAnalyticsService creates a new instance of IAnalyticsService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIAnalyticsService(t interface {
	mock.TestingT
	Cleanup(func())
}) *IAnalyticsService {
	mock := &IAnalyticsService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// IAnalyticsService is an autogenerated mock type for the IAnalyticsService type
type IAnalyticsService struct {
	mock.Mock
}

type IAnalyticsService_Expecter struct {
	mock *mock.Mock
}

func (_m *IAnalyticsService) EXPECT() *IAnalyticsService_Expecter {
	return &IAnalyticsService_Expecter{mock: &_m.Mock}
}

// GetEvents provides a mock function for the type IAnalyticsService
func (_mock *IAnalyticsService) GetEvents(ctx context.Context, limit int32, offset int32) (*analytics.GetEventsResponse, error) {
	ret := _mock.Called(ctx, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for GetEvents")
	}

	var r0 *analytics.GetEventsResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int32, int32) (*analytics.GetEventsResponse, error)); ok {
		return returnFunc(ctx, limit, offset)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int32, int32) *analytics.GetEventsResponse); ok {
		r0 = returnFunc(ctx, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*analytics.GetEventsResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int32, int32) error); ok {
		r1 = returnFunc(ctx, limit, offset)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// IAnalyticsService_GetEvents_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetEvents'
type IAnalyticsService_GetEvents_Call struct {
	*mock.Call
}

// GetEvents is a helper method to define mock.On call
//   - ctx context.Context
//   - limit int32
//   - offset int32
func (_e *IAnalyticsService_Expecter) GetEvents(ctx interface{}, limit interface{}, offset interface{}) *IAnalyticsService_GetEvents_Call {
	return &IAnalyticsService_GetEvents_Call{Call: _e.mock.On("GetEvents", ctx, limit, offset)}
}

func (_c *IAnalyticsService_GetEvents_Call) Run(run func(ctx context.Context, limit int32, offset int32)) *IAnalyticsService_GetEvents_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int32
		if args[1] != nil {
			arg1 = args[1].(int32)
		}
		var arg2 int32
		if args[2] != nil {
			arg2 = args[2].(int32)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *IAnalyticsService_GetEvents_Call) Return(getEventsResponse *analytics.GetEventsResponse, err error) *IAnalyticsService_GetEvents_Call {
	_c.Call.Return(getEventsResponse, err)
	return _c
}

func (_c *IAnalyticsService_GetEvents_Call) RunAndReturn(run func(ctx context.Context, limit int32, offset int32) (*analytics.GetEventsResponse, error)) *IAnalyticsService_GetEvents_Call {
	_c.Call.Return(run)
	return _c
}

// GetLinkStats provides a mock function for the type IAnalyticsService
func (_mock *IAnalyticsService) GetLinkStats(ctx context.Context, shortLink string) (*analytics.GetLinkStatsResponse, error) {
	ret := _mock.Called(ctx, shortLink)

	if len(ret) == 0 {
		panic("no return value specified for GetLinkStats")
	}

	var r0 *analytics.GetLinkStatsResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*analytics.GetLinkStatsResponse, error)); ok {
		return returnFunc(ctx, shortLink)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *analytics.GetLinkStatsResponse); ok {
		r0 = returnFunc(ctx, shortLink)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*analytics.GetLinkStatsResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, shortLink)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// IAnalyticsService_GetLinkStats_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetLinkStats'
type IAnalyticsService_GetLinkStats_Call struct {
	*mock.Call
}

// GetLinkStats is a helper method to define mock.On call
//   - ctx context.Context
//   - shortLink string
func (_e *IAnalyticsService_Expecter) GetLinkStats(ctx interface{}, shortLink interface{}) *IAnalyticsService_GetLinkStats_Call {
	return &IAnalyticsService_GetLinkStats_Call{Call: _e.mock.On("GetLinkStats", ctx, shortLink)}
}

func (_c *IAnalyticsService_GetLinkStats_Call) Run(run func(ctx context.Context, shortLink string)) *IAnalyticsService_GetLinkStats_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *IAnalyticsService_GetLinkStats_Call) Return(getLinkStatsResponse *analytics.GetLinkStatsResponse, err error) *IAnalyticsService_GetLinkStats_Call {
	_c.Call.Return(getLinkStatsResponse, err)
	return _c
}

func (_c *IAnalyticsService_GetLinkStats_Call) RunAndReturn(run func(ctx context.Context, shortLink string) (*analytics.GetLinkStatsResponse, error)) *IAnalyticsService_GetLinkStats_Call {
	_c.Call.Return(run)
	return _c
}

// RecordEvent provides a mock function for the type IAnalyticsService
func (_mock *IAnalyticsService) RecordEvent(ctx context.Context, req *analytics.RecordEventRequest) error {
	ret := _mock.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for RecordEvent")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *analytics.RecordEventRequest) error); ok {
		r0 = returnFunc(ctx, req)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// IAnalyticsService_RecordEvent_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RecordEvent'
type IAnalyticsService_RecordEvent_Call struct {
	*mock.Call
}

// RecordEvent is a helper method to define mock.On call
//   - ctx context.Context
//   - req *analytics.RecordEventRequest
func (_e *IAnalyticsService_Expecter) RecordEvent(ctx interface{}, req interface{}) *IAnalyticsService_RecordEvent_Call {
	return &IAnalyticsService_RecordEvent_Call{Call: _e.mock.On("RecordEvent", ctx, req)}
}

func (_c *IAnalyticsService_RecordEvent_Call) Run(run func(ctx context.Context, req *analytics.RecordEventRequest)) *IAnalyticsService_RecordEvent_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *analytics.RecordEventRequest
		if args[1] != nil {
			arg1 = args[1].(*analytics.RecordEventRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *IAnalyticsService_RecordEvent_Call) Return(err error) *IAnalyticsService_RecordEvent_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *IAnalyticsService_RecordEvent_Call) RunAndReturn(run func(ctx context.Context, req *analytics.RecordEventRequest) error) *IAnalyticsService_RecordEvent_Call {
	_c.Call.Return(run)
	return _c
}
