// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/egor200512/URL_shortener/shared/gen/analytics"
	mock "github.com/stretchr/testify/mock"
	"google.golang.org/protobuf/types/known/emptypb"
)

// NewMockIAnalyticsService creates a new instance of MockIAnalyticsService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIAnalyticsService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIAnalyticsService {
	mock := &MockIAnalyticsService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockIAnalyticsService is an autogenerated mock type for the IAnalyticsService type
type MockIAnalyticsService struct {
	mock.Mock
}

type MockIAnalyticsService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIAnalyticsService) EXPECT() *MockIAnalyticsService_Expecter {
	return &MockIAnalyticsService_Expecter{mock: &_m.Mock}
}

// GetEvents provides a mock function for the type MockIAnalyticsService
func (_mock *MockIAnalyticsService) GetEvents(ctx context.Context, req *analytics.GetEventsRequest) (*analytics.GetEventsResponse, error) {
	ret := _mock.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for GetEvents")
	}

	var r0 *analytics.GetEventsResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *analytics.GetEventsRequest) (*analytics.GetEventsResponse, error)); ok {
		return returnFunc(ctx, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *analytics.GetEventsRequest) *analytics.GetEventsResponse); ok {
		r0 = returnFunc(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*analytics.GetEventsResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *analytics.GetEventsRequest) error); ok {
		r1 = returnFunc(ctx, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIAnalyticsService_GetEvents_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetEvents'
type MockIAnalyticsService_GetEvents_Call struct {
	*mock.Call
}

// GetEvents is a helper method to define mock.On call
//   - ctx context.Context
//   - req *analytics.GetEventsRequest
func (_e *MockIAnalyticsService_Expecter) GetEvents(ctx interface{}, req interface{}) *MockIAnalyticsService_GetEvents_Call {
	return &MockIAnalyticsService_GetEvents_Call{Call: _e.mock.On("GetEvents", ctx, req)}
}

func (_c *MockIAnalyticsService_GetEvents_Call) Run(run func(ctx context.Context, req *analytics.GetEventsRequest)) *MockIAnalyticsService_GetEvents_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *analytics.GetEventsRequest
		if args[1] != nil {
			arg1 = args[1].(*analytics.GetEventsRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIAnalyticsService_GetEvents_Call) Return(getEventsResponse *analytics.GetEventsResponse, err error) *MockIAnalyticsService_GetEvents_Call {
	_c.Call.Return(getEventsResponse, err)
	return _c
}

func (_c *MockIAnalyticsService_GetEvents_Call) RunAndReturn(run func(ctx context.Context, req *analytics.GetEventsRequest) (*analytics.GetEventsResponse, error)) *MockIAnalyticsService_GetEvents_Call {
	_c.Call.Return(run)
	return _c
}

// Health provides a mock function for the type MockIAnalyticsService
func (_mock *MockIAnalyticsService) Health(ctx context.Context, req *emptypb.Empty) (*emptypb.Empty, error) {
	ret := _mock.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for Health")
	}

	var r0 *emptypb.Empty
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *emptypb.Empty) (*emptypb.Empty, error)); ok {
		return returnFunc(ctx, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *emptypb.Empty) *emptypb.Empty); ok {
		r0 = returnFunc(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*emptypb.Empty)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *emptypb.Empty) error); ok {
		r1 = returnFunc(ctx, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIAnalyticsService_Health_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Health'
type MockIAnalyticsService_Health_Call struct {
	*mock.Call
}

// Health is a helper method to define mock.On call
//   - ctx context.Context
//   - req *emptypb.Empty
func (_e *MockIAnalyticsService_Expecter) Health(ctx interface{}, req interface{}) *MockIAnalyticsService_Health_Call {
	return &MockIAnalyticsService_Health_Call{Call: _e.mock.On("Health", ctx, req)}
}

func (_c *MockIAnalyticsService_Health_Call) Run(run func(ctx context.Context, req *emptypb.Empty)) *MockIAnalyticsService_Health_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *emptypb.Empty
		if args[1] != nil {
			arg1 = args[1].(*emptypb.Empty)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIAnalyticsService_Health_Call) Return(empty *emptypb.Empty, err error) *MockIAnalyticsService_Health_Call {
	_c.Call.Return(empty, err)
	return _c
}

func (_c *MockIAnalyticsService_Health_Call) RunAndReturn(run func(ctx context.Context, req *emptypb.Empty) (*emptypb.Empty, error)) *MockIAnalyticsService_Health_Call {
	_c.Call.Return(run)
	return _c
}
