// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/egor200512/URL_shortener/shared/models"
	mock "github.com/stretchr/testify/mock"
)

// NewMockIAnalyticsRepo creates a new instance of MockIAnalyticsRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIAnalyticsRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIAnalyticsRepo {
	mock := &MockIAnalyticsRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockIAnalyticsRepo is an autogenerated mock type for the IAnalyticsRepo type
type MockIAnalyticsRepo struct {
	mock.Mock
}

type MockIAnalyticsRepo_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIAnalyticsRepo) EXPECT() *MockIAnalyticsRepo_Expecter {
	return &MockIAnalyticsRepo_Expecter{mock: &_m.Mock}
}

// GetEvents provides a mock function for the type MockIAnalyticsRepo
func (_mock *MockIAnalyticsRepo) GetEvents(ctx context.Context, limit int32, offset int32) ([]*models.LinkEvent, error) {
	ret := _mock.Called(ctx, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for GetEvents")
	}

	var r0 []*models.LinkEvent
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int32, int32) ([]*models.LinkEvent, error)); ok {
		return returnFunc(ctx, limit, offset)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int32, int32) []*models.LinkEvent); ok {
		r0 = returnFunc(ctx, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.LinkEvent)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int32, int32) error); ok {
		r1 = returnFunc(ctx, limit, offset)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIAnalyticsRepo_GetEvents_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetEvents'
type MockIAnalyticsRepo_GetEvents_Call struct {
	*mock.Call
}

// GetEvents is a helper method to define mock.On call
//   - ctx context.Context
//   - limit int32
//   - offset int32
func (_e *MockIAnalyticsRepo_Expecter) GetEvents(ctx interface{}, limit interface{}, offset interface{}) *MockIAnalyticsRepo_GetEvents_Call {
	return &MockIAnalyticsRepo_GetEvents_Call{Call: _e.mock.On("GetEvents", ctx, limit, offset)}
}

func (_c *MockIAnalyticsRepo_GetEvents_Call) Run(run func(ctx context.Context, limit int32, offset int32)) *MockIAnalyticsRepo_GetEvents_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int32
		if args[1] != nil {
			arg1 = args[1].(int32)
		}
		var arg2 int32
		if args[2] != nil {
			arg2 = args[2].(int32)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockIAnalyticsRepo_GetEvents_Call) Return(linkEvents []*models.LinkEvent, err error) *MockIAnalyticsRepo_GetEvents_Call {
	_c.Call.Return(linkEvents, err)
	return _c
}

func (_c *MockIAnalyticsRepo_GetEvents_Call) RunAndReturn(run func(ctx context.Context, limit int32, offset int32) ([]*models.LinkEvent, error)) *MockIAnalyticsRepo_GetEvents_Call {
	_c.Call.Return(run)
	return _c
}

// InsertEvent provides a mock function for the type MockIAnalyticsRepo
func (_mock *MockIAnalyticsRepo) InsertEvent(ctx context.Context, payload *models.LinkEvent) error {
	ret := _mock.Called(ctx, payload)

	if len(ret) == 0 {
		panic("no return value specified for InsertEvent")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *models.LinkEvent) error); ok {
		r0 = returnFunc(ctx, payload)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIAnalyticsRepo_InsertEvent_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InsertEvent'
type MockIAnalyticsRepo_InsertEvent_Call struct {
	*mock.Call
}

// InsertEvent is a helper method to define mock.On call
//   - ctx context.Context
//   - payload *models.LinkEvent
func (_e *MockIAnalyticsRepo_Expecter) InsertEvent(ctx interface{}, payload interface{}) *MockIAnalyticsRepo_InsertEvent_Call {
	return &MockIAnalyticsRepo_InsertEvent_Call{Call: _e.mock.On("InsertEvent", ctx, payload)}
}

func (_c *MockIAnalyticsRepo_InsertEvent_Call) Run(run func(ctx context.Context, payload *models.LinkEvent)) *MockIAnalyticsRepo_InsertEvent_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *models.LinkEvent
		if args[1] != nil {
			arg1 = args[1].(*models.LinkEvent)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIAnalyticsRepo_InsertEvent_Call) Return(err error) *MockIAnalyticsRepo_InsertEvent_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIAnalyticsRepo_InsertEvent_Call) RunAndReturn(run func(ctx context.Context, payload *models.LinkEvent) error) *MockIAnalyticsRepo_InsertEvent_Call {
	_c.Call.Return(run)
	return _c
}
