// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package app

import (
	"context"
)

// Injectors from wireInit.go:

func InitServerApp(ctx context.Context) (*App, func(), error) {
	httpConf, err := ProvideHttpConf()
	if err != nil {
		return nil, nil, err
	}
	grpcConf, err := ProvideGrpcConf()
	if err != nil {
		return nil, nil, err
	}
	pgConf, err := ProvidePgConf()
	if err != nil {
		return nil, nil, err
	}
	pool, err := ProvidePgPool(ctx, pgConf)
	if err != nil {
		return nil, nil, err
	}
	iAuthRepo := ProvideAuthRepo(ctx, pool)
	iJwtConf, err := ProvideJwtConf()
	if err != nil {
		return nil, nil, err
	}
	iAuthService := ProvideAuthService(iAuthRepo, iJwtConf)
	authServiceServer := ProvideAuthHandler(iAuthService)
	app := &App{
		HttpConf:    httpConf,
		GrpcConf:    grpcConf,
		AuthHandler: authServiceServer,
	}
	return app, func() {
	}, nil
}
