// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"time"

	mock "github.com/stretchr/testify/mock"
)

// NewIJwtConf creates a new instance of IJwtConf. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIJwtConf(t interface {
	mock.TestingT
	Cleanup(func())
}) *IJwtConf {
	mock := &IJwtConf{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// IJwtConf is an autogenerated mock type for the IJwtConf type
type IJwtConf struct {
	mock.Mock
}

type IJwtConf_Expecter struct {
	mock *mock.Mock
}

func (_m *IJwtConf) EXPECT() *IJwtConf_Expecter {
	return &IJwtConf_Expecter{mock: &_m.Mock}
}

// AccessExp provides a mock function for the type IJwtConf
func (_mock *IJwtConf) AccessExp() time.Duration {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for AccessExp")
	}

	var r0 time.Duration
	if returnFunc, ok := ret.Get(0).(func() time.Duration); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(time.Duration)
	}
	return r0
}

// IJwtConf_AccessExp_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AccessExp'
type IJwtConf_AccessExp_Call struct {
	*mock.Call
}

// AccessExp is a helper method to define mock.On call
func (_e *IJwtConf_Expecter) AccessExp() *IJwtConf_AccessExp_Call {
	return &IJwtConf_AccessExp_Call{Call: _e.mock.On("AccessExp")}
}

func (_c *IJwtConf_AccessExp_Call) Run(run func()) *IJwtConf_AccessExp_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *IJwtConf_AccessExp_Call) Return(duration time.Duration) *IJwtConf_AccessExp_Call {
	_c.Call.Return(duration)
	return _c
}

func (_c *IJwtConf_AccessExp_Call) RunAndReturn(run func() time.Duration) *IJwtConf_AccessExp_Call {
	_c.Call.Return(run)
	return _c
}

// Secret provides a mock function for the type IJwtConf
func (_mock *IJwtConf) Secret() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Secret")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// IJwtConf_Secret_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Secret'
type IJwtConf_Secret_Call struct {
	*mock.Call
}

// Secret is a helper method to define mock.On call
func (_e *IJwtConf_Expecter) Secret() *IJwtConf_Secret_Call {
	return &IJwtConf_Secret_Call{Call: _e.mock.On("Secret")}
}

func (_c *IJwtConf_Secret_Call) Run(run func()) *IJwtConf_Secret_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *IJwtConf_Secret_Call) Return(s string) *IJwtConf_Secret_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *IJwtConf_Secret_Call) RunAndReturn(run func() string) *IJwtConf_Secret_Call {
	_c.Call.Return(run)
	return _c
}
