// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/egor200512/URL_shortener/services/auth/internal/models"
	mock "github.com/stretchr/testify/mock"
)

// NewIAuthRepo creates a new instance of IAuthRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIAuthRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *IAuthRepo {
	mock := &IAuthRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// IAuthRepo is an autogenerated mock type for the IAuthRepo type
type IAuthRepo struct {
	mock.Mock
}

type IAuthRepo_Expecter struct {
	mock *mock.Mock
}

func (_m *IAuthRepo) EXPECT() *IAuthRepo_Expecter {
	return &IAuthRepo_Expecter{mock: &_m.Mock}
}

// CheckRegistration provides a mock function for the type IAuthRepo
func (_mock *IAuthRepo) CheckRegistration(ctx context.Context, email string) (*models.User, error) {
	ret := _mock.Called(ctx, email)

	if len(ret) == 0 {
		panic("no return value specified for CheckRegistration")
	}

	var r0 *models.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*models.User, error)); ok {
		return returnFunc(ctx, email)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *models.User); ok {
		r0 = returnFunc(ctx, email)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, email)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// IAuthRepo_CheckRegistration_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CheckRegistration'
type IAuthRepo_CheckRegistration_Call struct {
	*mock.Call
}

// CheckRegistration is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
func (_e *IAuthRepo_Expecter) CheckRegistration(ctx interface{}, email interface{}) *IAuthRepo_CheckRegistration_Call {
	return &IAuthRepo_CheckRegistration_Call{Call: _e.mock.On("CheckRegistration", ctx, email)}
}

func (_c *IAuthRepo_CheckRegistration_Call) Run(run func(ctx context.Context, email string)) *IAuthRepo_CheckRegistration_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *IAuthRepo_CheckRegistration_Call) Return(user *models.User, err error) *IAuthRepo_CheckRegistration_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *IAuthRepo_CheckRegistration_Call) RunAndReturn(run func(ctx context.Context, email string) (*models.User, error)) *IAuthRepo_CheckRegistration_Call {
	_c.Call.Return(run)
	return _c
}

// InsertUser provides a mock function for the type IAuthRepo
func (_mock *IAuthRepo) InsertUser(ctx context.Context, regRequest *models.RegisterRequest) error {
	ret := _mock.Called(ctx, regRequest)

	if len(ret) == 0 {
		panic("no return value specified for InsertUser")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *models.RegisterRequest) error); ok {
		r0 = returnFunc(ctx, regRequest)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// IAuthRepo_InsertUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InsertUser'
type IAuthRepo_InsertUser_Call struct {
	*mock.Call
}

// InsertUser is a helper method to define mock.On call
//   - ctx context.Context
//   - regRequest *models.RegisterRequest
func (_e *IAuthRepo_Expecter) InsertUser(ctx interface{}, regRequest interface{}) *IAuthRepo_InsertUser_Call {
	return &IAuthRepo_InsertUser_Call{Call: _e.mock.On("InsertUser", ctx, regRequest)}
}

func (_c *IAuthRepo_InsertUser_Call) Run(run func(ctx context.Context, regRequest *models.RegisterRequest)) *IAuthRepo_InsertUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *models.RegisterRequest
		if args[1] != nil {
			arg1 = args[1].(*models.RegisterRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *IAuthRepo_InsertUser_Call) Return(err error) *IAuthRepo_InsertUser_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *IAuthRepo_InsertUser_Call) RunAndReturn(run func(ctx context.Context, regRequest *models.RegisterRequest) error) *IAuthRepo_InsertUser_Call {
	_c.Call.Return(run)
	return _c
}
