// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/egor200512/URL_shortener/services/auth/internal/models"
	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewMockIAuthService creates a new instance of MockIAuthService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIAuthService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIAuthService {
	mock := &MockIAuthService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockIAuthService is an autogenerated mock type for the IAuthService type
type MockIAuthService struct {
	mock.Mock
}

type MockIAuthService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIAuthService) EXPECT() *MockIAuthService_Expecter {
	return &MockIAuthService_Expecter{mock: &_m.Mock}
}

// Login provides a mock function for the type MockIAuthService
func (_mock *MockIAuthService) Login(ctx context.Context, email string, password string) (*models.AccessToken, error) {
	ret := _mock.Called(ctx, email, password)

	if len(ret) == 0 {
		panic("no return value specified for Login")
	}

	var r0 *models.AccessToken
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (*models.AccessToken, error)); ok {
		return returnFunc(ctx, email, password)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) *models.AccessToken); ok {
		r0 = returnFunc(ctx, email, password)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.AccessToken)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, email, password)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIAuthService_Login_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Login'
type MockIAuthService_Login_Call struct {
	*mock.Call
}

// Login is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
//   - password string
func (_e *MockIAuthService_Expecter) Login(ctx interface{}, email interface{}, password interface{}) *MockIAuthService_Login_Call {
	return &MockIAuthService_Login_Call{Call: _e.mock.On("Login", ctx, email, password)}
}

func (_c *MockIAuthService_Login_Call) Run(run func(ctx context.Context, email string, password string)) *MockIAuthService_Login_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockIAuthService_Login_Call) Return(accessToken *models.AccessToken, err error) *MockIAuthService_Login_Call {
	_c.Call.Return(accessToken, err)
	return _c
}

func (_c *MockIAuthService_Login_Call) RunAndReturn(run func(ctx context.Context, email string, password string) (*models.AccessToken, error)) *MockIAuthService_Login_Call {
	_c.Call.Return(run)
	return _c
}

// Register provides a mock function for the type MockIAuthService
func (_mock *MockIAuthService) Register(ctx context.Context, email string, password string) error {
	ret := _mock.Called(ctx, email, password)

	if len(ret) == 0 {
		panic("no return value specified for Register")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = returnFunc(ctx, email, password)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIAuthService_Register_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Register'
type MockIAuthService_Register_Call struct {
	*mock.Call
}

// Register is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
//   - password string
func (_e *MockIAuthService_Expecter) Register(ctx interface{}, email interface{}, password interface{}) *MockIAuthService_Register_Call {
	return &MockIAuthService_Register_Call{Call: _e.mock.On("Register", ctx, email, password)}
}

func (_c *MockIAuthService_Register_Call) Run(run func(ctx context.Context, email string, password string)) *MockIAuthService_Register_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockIAuthService_Register_Call) Return(err error) *MockIAuthService_Register_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIAuthService_Register_Call) RunAndReturn(run func(ctx context.Context, email string, password string) error) *MockIAuthService_Register_Call {
	_c.Call.Return(run)
	return _c
}

// VerifyToken provides a mock function for the type MockIAuthService
func (_mock *MockIAuthService) VerifyToken(ctx context.Context, token string) (uuid.UUID, error) {
	ret := _mock.Called(ctx, token)

	if len(ret) == 0 {
		panic("no return value specified for VerifyToken")
	}

	var r0 uuid.UUID
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (uuid.UUID, error)); ok {
		return returnFunc(ctx, token)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) uuid.UUID); ok {
		r0 = returnFunc(ctx, token)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(uuid.UUID)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, token)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIAuthService_VerifyToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'VerifyToken'
type MockIAuthService_VerifyToken_Call struct {
	*mock.Call
}

// VerifyToken is a helper method to define mock.On call
//   - ctx context.Context
//   - token string
func (_e *MockIAuthService_Expecter) VerifyToken(ctx interface{}, token interface{}) *MockIAuthService_VerifyToken_Call {
	return &MockIAuthService_VerifyToken_Call{Call: _e.mock.On("VerifyToken", ctx, token)}
}

func (_c *MockIAuthService_VerifyToken_Call) Run(run func(ctx context.Context, token string)) *MockIAuthService_VerifyToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIAuthService_VerifyToken_Call) Return(uUID uuid.UUID, err error) *MockIAuthService_VerifyToken_Call {
	_c.Call.Return(uUID, err)
	return _c
}

func (_c *MockIAuthService_VerifyToken_Call) RunAndReturn(run func(ctx context.Context, token string) (uuid.UUID, error)) *MockIAuthService_VerifyToken_Call {
	_c.Call.Return(run)
	return _c
}
