links_avg_per_user_all:
  query: |
    SELECT COALESCE(AVG(cnt), 0) AS avg_links_per_user_all
    FROM (
      SELECT user_id, COUNT(*)::float AS cnt
      FROM links.short_links
      GROUP BY user_id
    ) s;
  metrics:
    - avg_links_per_user_all:
        usage: GAUGE
        description: "Average links per user (all time)"
