// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package app

import (
	"context"
)

// Injectors from wireInit.go:

func InitServerApp(ctx context.Context) (*App, func(), error) {
	httpConf, err := ProvideHttpConf()
	if err != nil {
		return nil, nil, err
	}
	grpcConf, err := ProvideGrpcConf()
	if err != nil {
		return nil, nil, err
	}
	pgConf, err := ProvidePgConf()
	if err != nil {
		return nil, nil, err
	}
	pool, err := ProvidePgPool(ctx, pgConf)
	if err != nil {
		return nil, nil, err
	}
	iLinksRepo := ProvideLinksRepo(ctx, pool)
	iJwtConf, err := ProvideJwtConf()
	if err != nil {
		return nil, nil, err
	}
	iLinksService := ProvideLinksService(iLinksRepo, iJwtConf)
	linksServiceServer := ProvideLinksHandler(iLinksService)
	app := &App{
		HttpConf:     httpConf,
		GrpcConf:     grpcConf,
		LinksHandler: linksServiceServer,
	}
	return app, func() {
	}, nil
}
