// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/egor200512/URL_shortener/services/links/models"
	mock "github.com/stretchr/testify/mock"
)

// NewICache creates a new instance of ICache. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewICache(t interface {
	mock.TestingT
	Cleanup(func())
}) *ICache {
	mock := &ICache{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// ICache is an autogenerated mock type for the ICache type
type ICache struct {
	mock.Mock
}

type ICache_Expecter struct {
	mock *mock.Mock
}

func (_m *ICache) EXPECT() *ICache_Expecter {
	return &ICache_Expecter{mock: &_m.Mock}
}

// DelShort provides a mock function for the type ICache
func (_mock *ICache) DelShort(ctx context.Context, shortLink string) error {
	ret := _mock.Called(ctx, shortLink)

	if len(ret) == 0 {
		panic("no return value specified for DelShort")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, shortLink)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// ICache_DelShort_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DelShort'
type ICache_DelShort_Call struct {
	*mock.Call
}

// DelShort is a helper method to define mock.On call
//   - ctx context.Context
//   - shortLink string
func (_e *ICache_Expecter) DelShort(ctx interface{}, shortLink interface{}) *ICache_DelShort_Call {
	return &ICache_DelShort_Call{Call: _e.mock.On("DelShort", ctx, shortLink)}
}

func (_c *ICache_DelShort_Call) Run(run func(ctx context.Context, shortLink string)) *ICache_DelShort_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *ICache_DelShort_Call) Return(err error) *ICache_DelShort_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *ICache_DelShort_Call) RunAndReturn(run func(ctx context.Context, shortLink string) error) *ICache_DelShort_Call {
	_c.Call.Return(run)
	return _c
}

// GetShort provides a mock function for the type ICache
func (_mock *ICache) GetShort(ctx context.Context, shortLink string) (*models.Link, error) {
	ret := _mock.Called(ctx, shortLink)

	if len(ret) == 0 {
		panic("no return value specified for GetShort")
	}

	var r0 *models.Link
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*models.Link, error)); ok {
		return returnFunc(ctx, shortLink)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *models.Link); ok {
		r0 = returnFunc(ctx, shortLink)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Link)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, shortLink)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// ICache_GetShort_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetShort'
type ICache_GetShort_Call struct {
	*mock.Call
}

// GetShort is a helper method to define mock.On call
//   - ctx context.Context
//   - shortLink string
func (_e *ICache_Expecter) GetShort(ctx interface{}, shortLink interface{}) *ICache_GetShort_Call {
	return &ICache_GetShort_Call{Call: _e.mock.On("GetShort", ctx, shortLink)}
}

func (_c *ICache_GetShort_Call) Run(run func(ctx context.Context, shortLink string)) *ICache_GetShort_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *ICache_GetShort_Call) Return(link *models.Link, err error) *ICache_GetShort_Call {
	_c.Call.Return(link, err)
	return _c
}

func (_c *ICache_GetShort_Call) RunAndReturn(run func(ctx context.Context, shortLink string) (*models.Link, error)) *ICache_GetShort_Call {
	_c.Call.Return(run)
	return _c
}

// SetShort provides a mock function for the type ICache
func (_mock *ICache) SetShort(ctx context.Context, shortLink string, link *models.Link) error {
	ret := _mock.Called(ctx, shortLink, link)

	if len(ret) == 0 {
		panic("no return value specified for SetShort")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, *models.Link) error); ok {
		r0 = returnFunc(ctx, shortLink, link)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// ICache_SetShort_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetShort'
type ICache_SetShort_Call struct {
	*mock.Call
}

// SetShort is a helper method to define mock.On call
//   - ctx context.Context
//   - shortLink string
//   - link *models.Link
func (_e *ICache_Expecter) SetShort(ctx interface{}, shortLink interface{}, link interface{}) *ICache_SetShort_Call {
	return &ICache_SetShort_Call{Call: _e.mock.On("SetShort", ctx, shortLink, link)}
}

func (_c *ICache_SetShort_Call) Run(run func(ctx context.Context, shortLink string, link *models.Link)) *ICache_SetShort_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 *models.Link
		if args[2] != nil {
			arg2 = args[2].(*models.Link)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *ICache_SetShort_Call) Return(err error) *ICache_SetShort_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *ICache_SetShort_Call) RunAndReturn(run func(ctx context.Context, shortLink string, link *models.Link) error) *ICache_SetShort_Call {
	_c.Call.Return(run)
	return _c
}
