// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewIProducer creates a new instance of IProducer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIProducer(t interface {
	mock.TestingT
	Cleanup(func())
}) *IProducer {
	mock := &IProducer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// IProducer is an autogenerated mock type for the IProducer type
type IProducer struct {
	mock.Mock
}

type IProducer_Expecter struct {
	mock *mock.Mock
}

func (_m *IProducer) EXPECT() *IProducer_Expecter {
	return &IProducer_Expecter{mock: &_m.Mock}
}

// Close provides a mock function for the type IProducer
func (_mock *IProducer) Close() {
	_mock.Called()
	return
}

// IProducer_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type IProducer_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *IProducer_Expecter) Close() *IProducer_Close_Call {
	return &IProducer_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *IProducer_Close_Call) Run(run func()) *IProducer_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *IProducer_Close_Call) Return() *IProducer_Close_Call {
	_c.Call.Return()
	return _c
}

func (_c *IProducer_Close_Call) RunAndReturn(run func()) *IProducer_Close_Call {
	_c.Run(run)
	return _c
}

// Publish provides a mock function for the type IProducer
func (_mock *IProducer) Publish(ctx context.Context, subject string, payload []byte) error {
	ret := _mock.Called(ctx, subject, payload)

	if len(ret) == 0 {
		panic("no return value specified for Publish")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, []byte) error); ok {
		r0 = returnFunc(ctx, subject, payload)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// IProducer_Publish_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Publish'
type IProducer_Publish_Call struct {
	*mock.Call
}

// Publish is a helper method to define mock.On call
//   - ctx context.Context
//   - subject string
//   - payload []byte
func (_e *IProducer_Expecter) Publish(ctx interface{}, subject interface{}, payload interface{}) *IProducer_Publish_Call {
	return &IProducer_Publish_Call{Call: _e.mock.On("Publish", ctx, subject, payload)}
}

func (_c *IProducer_Publish_Call) Run(run func(ctx context.Context, subject string, payload []byte)) *IProducer_Publish_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []byte
		if args[2] != nil {
			arg2 = args[2].([]byte)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *IProducer_Publish_Call) Return(err error) *IProducer_Publish_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *IProducer_Publish_Call) RunAndReturn(run func(ctx context.Context, subject string, payload []byte) error) *IProducer_Publish_Call {
	_c.Call.Return(run)
	return _c
}

// Subject provides a mock function for the type IProducer
func (_mock *IProducer) Subject(eventType string) string {
	ret := _mock.Called(eventType)

	if len(ret) == 0 {
		panic("no return value specified for Subject")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func(string) string); ok {
		r0 = returnFunc(eventType)
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// IProducer_Subject_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Subject'
type IProducer_Subject_Call struct {
	*mock.Call
}

// Subject is a helper method to define mock.On call
//   - eventType string
func (_e *IProducer_Expecter) Subject(eventType interface{}) *IProducer_Subject_Call {
	return &IProducer_Subject_Call{Call: _e.mock.On("Subject", eventType)}
}

func (_c *IProducer_Subject_Call) Run(run func(eventType string)) *IProducer_Subject_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *IProducer_Subject_Call) Return(s string) *IProducer_Subject_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *IProducer_Subject_Call) RunAndReturn(run func(eventType string) string) *IProducer_Subject_Call {
	_c.Call.Return(run)
	return _c
}
