// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/egor200512/URL_shortener/services/links/models"
	mock "github.com/stretchr/testify/mock"
)

// NewILinksRepo creates a new instance of ILinksRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewILinksRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *ILinksRepo {
	mock := &ILinksRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// ILinksRepo is an autogenerated mock type for the ILinksRepo type
type ILinksRepo struct {
	mock.Mock
}

type ILinksRepo_Expecter struct {
	mock *mock.Mock
}

func (_m *ILinksRepo) EXPECT() *ILinksRepo_Expecter {
	return &ILinksRepo_Expecter{mock: &_m.Mock}
}

// DeleteLink provides a mock function for the type ILinksRepo
func (_mock *ILinksRepo) DeleteLink(ctx context.Context, shortLink string, userID string) error {
	ret := _mock.Called(ctx, shortLink, userID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteLink")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = returnFunc(ctx, shortLink, userID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// ILinksRepo_DeleteLink_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteLink'
type ILinksRepo_DeleteLink_Call struct {
	*mock.Call
}

// DeleteLink is a helper method to define mock.On call
//   - ctx context.Context
//   - shortLink string
//   - userID string
func (_e *ILinksRepo_Expecter) DeleteLink(ctx interface{}, shortLink interface{}, userID interface{}) *ILinksRepo_DeleteLink_Call {
	return &ILinksRepo_DeleteLink_Call{Call: _e.mock.On("DeleteLink", ctx, shortLink, userID)}
}

func (_c *ILinksRepo_DeleteLink_Call) Run(run func(ctx context.Context, shortLink string, userID string)) *ILinksRepo_DeleteLink_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *ILinksRepo_DeleteLink_Call) Return(err error) *ILinksRepo_DeleteLink_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *ILinksRepo_DeleteLink_Call) RunAndReturn(run func(ctx context.Context, shortLink string, userID string) error) *ILinksRepo_DeleteLink_Call {
	_c.Call.Return(run)
	return _c
}

// GetByOriginalLink provides a mock function for the type ILinksRepo
func (_mock *ILinksRepo) GetByOriginalLink(ctx context.Context, originalLink string) (*models.Link, error) {
	ret := _mock.Called(ctx, originalLink)

	if len(ret) == 0 {
		panic("no return value specified for GetByOriginalLink")
	}

	var r0 *models.Link
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*models.Link, error)); ok {
		return returnFunc(ctx, originalLink)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *models.Link); ok {
		r0 = returnFunc(ctx, originalLink)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Link)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, originalLink)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// ILinksRepo_GetByOriginalLink_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByOriginalLink'
type ILinksRepo_GetByOriginalLink_Call struct {
	*mock.Call
}

// GetByOriginalLink is a helper method to define mock.On call
//   - ctx context.Context
//   - originalLink string
func (_e *ILinksRepo_Expecter) GetByOriginalLink(ctx interface{}, originalLink interface{}) *ILinksRepo_GetByOriginalLink_Call {
	return &ILinksRepo_GetByOriginalLink_Call{Call: _e.mock.On("GetByOriginalLink", ctx, originalLink)}
}

func (_c *ILinksRepo_GetByOriginalLink_Call) Run(run func(ctx context.Context, originalLink string)) *ILinksRepo_GetByOriginalLink_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *ILinksRepo_GetByOriginalLink_Call) Return(link *models.Link, err error) *ILinksRepo_GetByOriginalLink_Call {
	_c.Call.Return(link, err)
	return _c
}

func (_c *ILinksRepo_GetByOriginalLink_Call) RunAndReturn(run func(ctx context.Context, originalLink string) (*models.Link, error)) *ILinksRepo_GetByOriginalLink_Call {
	_c.Call.Return(run)
	return _c
}

// GetByShortLink provides a mock function for the type ILinksRepo
func (_mock *ILinksRepo) GetByShortLink(ctx context.Context, shortLink string) (*models.Link, error) {
	ret := _mock.Called(ctx, shortLink)

	if len(ret) == 0 {
		panic("no return value specified for GetByShortLink")
	}

	var r0 *models.Link
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*models.Link, error)); ok {
		return returnFunc(ctx, shortLink)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *models.Link); ok {
		r0 = returnFunc(ctx, shortLink)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Link)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, shortLink)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// ILinksRepo_GetByShortLink_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByShortLink'
type ILinksRepo_GetByShortLink_Call struct {
	*mock.Call
}

// GetByShortLink is a helper method to define mock.On call
//   - ctx context.Context
//   - shortLink string
func (_e *ILinksRepo_Expecter) GetByShortLink(ctx interface{}, shortLink interface{}) *ILinksRepo_GetByShortLink_Call {
	return &ILinksRepo_GetByShortLink_Call{Call: _e.mock.On("GetByShortLink", ctx, shortLink)}
}

func (_c *ILinksRepo_GetByShortLink_Call) Run(run func(ctx context.Context, shortLink string)) *ILinksRepo_GetByShortLink_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *ILinksRepo_GetByShortLink_Call) Return(link *models.Link, err error) *ILinksRepo_GetByShortLink_Call {
	_c.Call.Return(link, err)
	return _c
}

func (_c *ILinksRepo_GetByShortLink_Call) RunAndReturn(run func(ctx context.Context, shortLink string) (*models.Link, error)) *ILinksRepo_GetByShortLink_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserLinks provides a mock function for the type ILinksRepo
func (_mock *ILinksRepo) GetUserLinks(ctx context.Context, userID string, limit int32, offset int32) ([]string, int32, error) {
	ret := _mock.Called(ctx, userID, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for GetUserLinks")
	}

	var r0 []string
	var r1 int32
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, int32, int32) ([]string, int32, error)); ok {
		return returnFunc(ctx, userID, limit, offset)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, int32, int32) []string); ok {
		r0 = returnFunc(ctx, userID, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, int32, int32) int32); ok {
		r1 = returnFunc(ctx, userID, limit, offset)
	} else {
		r1 = ret.Get(1).(int32)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, string, int32, int32) error); ok {
		r2 = returnFunc(ctx, userID, limit, offset)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// ILinksRepo_GetUserLinks_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserLinks'
type ILinksRepo_GetUserLinks_Call struct {
	*mock.Call
}

// GetUserLinks is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - limit int32
//   - offset int32
func (_e *ILinksRepo_Expecter) GetUserLinks(ctx interface{}, userID interface{}, limit interface{}, offset interface{}) *ILinksRepo_GetUserLinks_Call {
	return &ILinksRepo_GetUserLinks_Call{Call: _e.mock.On("GetUserLinks", ctx, userID, limit, offset)}
}

func (_c *ILinksRepo_GetUserLinks_Call) Run(run func(ctx context.Context, userID string, limit int32, offset int32)) *ILinksRepo_GetUserLinks_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 int32
		if args[2] != nil {
			arg2 = args[2].(int32)
		}
		var arg3 int32
		if args[3] != nil {
			arg3 = args[3].(int32)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *ILinksRepo_GetUserLinks_Call) Return(strings []string, n int32, err error) *ILinksRepo_GetUserLinks_Call {
	_c.Call.Return(strings, n, err)
	return _c
}

func (_c *ILinksRepo_GetUserLinks_Call) RunAndReturn(run func(ctx context.Context, userID string, limit int32, offset int32) ([]string, int32, error)) *ILinksRepo_GetUserLinks_Call {
	_c.Call.Return(run)
	return _c
}

// InsertLink provides a mock function for the type ILinksRepo
func (_mock *ILinksRepo) InsertLink(ctx context.Context, req *models.CreateLinkReq) (*models.Link, error) {
	ret := _mock.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for InsertLink")
	}

	var r0 *models.Link
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *models.CreateLinkReq) (*models.Link, error)); ok {
		return returnFunc(ctx, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *models.CreateLinkReq) *models.Link); ok {
		r0 = returnFunc(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Link)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *models.CreateLinkReq) error); ok {
		r1 = returnFunc(ctx, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// ILinksRepo_InsertLink_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InsertLink'
type ILinksRepo_InsertLink_Call struct {
	*mock.Call
}

// InsertLink is a helper method to define mock.On call
//   - ctx context.Context
//   - req *models.CreateLinkReq
func (_e *ILinksRepo_Expecter) InsertLink(ctx interface{}, req interface{}) *ILinksRepo_InsertLink_Call {
	return &ILinksRepo_InsertLink_Call{Call: _e.mock.On("InsertLink", ctx, req)}
}

func (_c *ILinksRepo_InsertLink_Call) Run(run func(ctx context.Context, req *models.CreateLinkReq)) *ILinksRepo_InsertLink_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *models.CreateLinkReq
		if args[1] != nil {
			arg1 = args[1].(*models.CreateLinkReq)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *ILinksRepo_InsertLink_Call) Return(link *models.Link, err error) *ILinksRepo_InsertLink_Call {
	_c.Call.Return(link, err)
	return _c
}

func (_c *ILinksRepo_InsertLink_Call) RunAndReturn(run func(ctx context.Context, req *models.CreateLinkReq) (*models.Link, error)) *ILinksRepo_InsertLink_Call {
	_c.Call.Return(run)
	return _c
}
