// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"net/url"

	"github.com/egor200512/URL_shortener/services/links/models"
	mock "github.com/stretchr/testify/mock"
)

// NewMockILinksService creates a new instance of MockILinksService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockILinksService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockILinksService {
	mock := &MockILinksService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockILinksService is an autogenerated mock type for the ILinksService type
type MockILinksService struct {
	mock.Mock
}

type MockILinksService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockILinksService) EXPECT() *MockILinksService_Expecter {
	return &MockILinksService_Expecter{mock: &_m.Mock}
}

// CreateLink provides a mock function for the type MockILinksService
func (_mock *MockILinksService) CreateLink(context1 context.Context, uRL *url.URL) (string, error) {
	ret := _mock.Called(context1, uRL)

	if len(ret) == 0 {
		panic("no return value specified for CreateLink")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *url.URL) (string, error)); ok {
		return returnFunc(context1, uRL)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *url.URL) string); ok {
		r0 = returnFunc(context1, uRL)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *url.URL) error); ok {
		r1 = returnFunc(context1, uRL)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockILinksService_CreateLink_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateLink'
type MockILinksService_CreateLink_Call struct {
	*mock.Call
}

// CreateLink is a helper method to define mock.On call
//   - context1 context.Context
//   - uRL *url.URL
func (_e *MockILinksService_Expecter) CreateLink(context1 interface{}, uRL interface{}) *MockILinksService_CreateLink_Call {
	return &MockILinksService_CreateLink_Call{Call: _e.mock.On("CreateLink", context1, uRL)}
}

func (_c *MockILinksService_CreateLink_Call) Run(run func(context1 context.Context, uRL *url.URL)) *MockILinksService_CreateLink_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *url.URL
		if args[1] != nil {
			arg1 = args[1].(*url.URL)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockILinksService_CreateLink_Call) Return(s string, err error) *MockILinksService_CreateLink_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockILinksService_CreateLink_Call) RunAndReturn(run func(context1 context.Context, uRL *url.URL) (string, error)) *MockILinksService_CreateLink_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteLink provides a mock function for the type MockILinksService
func (_mock *MockILinksService) DeleteLink(ctx context.Context, shortLink string) error {
	ret := _mock.Called(ctx, shortLink)

	if len(ret) == 0 {
		panic("no return value specified for DeleteLink")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, shortLink)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockILinksService_DeleteLink_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteLink'
type MockILinksService_DeleteLink_Call struct {
	*mock.Call
}

// DeleteLink is a helper method to define mock.On call
//   - ctx context.Context
//   - shortLink string
func (_e *MockILinksService_Expecter) DeleteLink(ctx interface{}, shortLink interface{}) *MockILinksService_DeleteLink_Call {
	return &MockILinksService_DeleteLink_Call{Call: _e.mock.On("DeleteLink", ctx, shortLink)}
}

func (_c *MockILinksService_DeleteLink_Call) Run(run func(ctx context.Context, shortLink string)) *MockILinksService_DeleteLink_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockILinksService_DeleteLink_Call) Return(err error) *MockILinksService_DeleteLink_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockILinksService_DeleteLink_Call) RunAndReturn(run func(ctx context.Context, shortLink string) error) *MockILinksService_DeleteLink_Call {
	_c.Call.Return(run)
	return _c
}

// GetLinkInfo provides a mock function for the type MockILinksService
func (_mock *MockILinksService) GetLinkInfo(ctx context.Context, shortLink string) (*models.Link, error) {
	ret := _mock.Called(ctx, shortLink)

	if len(ret) == 0 {
		panic("no return value specified for GetLinkInfo")
	}

	var r0 *models.Link
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*models.Link, error)); ok {
		return returnFunc(ctx, shortLink)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *models.Link); ok {
		r0 = returnFunc(ctx, shortLink)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Link)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, shortLink)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockILinksService_GetLinkInfo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetLinkInfo'
type MockILinksService_GetLinkInfo_Call struct {
	*mock.Call
}

// GetLinkInfo is a helper method to define mock.On call
//   - ctx context.Context
//   - shortLink string
func (_e *MockILinksService_Expecter) GetLinkInfo(ctx interface{}, shortLink interface{}) *MockILinksService_GetLinkInfo_Call {
	return &MockILinksService_GetLinkInfo_Call{Call: _e.mock.On("GetLinkInfo", ctx, shortLink)}
}

func (_c *MockILinksService_GetLinkInfo_Call) Run(run func(ctx context.Context, shortLink string)) *MockILinksService_GetLinkInfo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockILinksService_GetLinkInfo_Call) Return(link *models.Link, err error) *MockILinksService_GetLinkInfo_Call {
	_c.Call.Return(link, err)
	return _c
}

func (_c *MockILinksService_GetLinkInfo_Call) RunAndReturn(run func(ctx context.Context, shortLink string) (*models.Link, error)) *MockILinksService_GetLinkInfo_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserLinks provides a mock function for the type MockILinksService
func (_mock *MockILinksService) GetUserLinks(ctx context.Context, limit int32, offset int32) ([]string, int32, error) {
	ret := _mock.Called(ctx, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for GetUserLinks")
	}

	var r0 []string
	var r1 int32
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int32, int32) ([]string, int32, error)); ok {
		return returnFunc(ctx, limit, offset)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int32, int32) []string); ok {
		r0 = returnFunc(ctx, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int32, int32) int32); ok {
		r1 = returnFunc(ctx, limit, offset)
	} else {
		r1 = ret.Get(1).(int32)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, int32, int32) error); ok {
		r2 = returnFunc(ctx, limit, offset)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockILinksService_GetUserLinks_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserLinks'
type MockILinksService_GetUserLinks_Call struct {
	*mock.Call
}

// GetUserLinks is a helper method to define mock.On call
//   - ctx context.Context
//   - limit int32
//   - offset int32
func (_e *MockILinksService_Expecter) GetUserLinks(ctx interface{}, limit interface{}, offset interface{}) *MockILinksService_GetUserLinks_Call {
	return &MockILinksService_GetUserLinks_Call{Call: _e.mock.On("GetUserLinks", ctx, limit, offset)}
}

func (_c *MockILinksService_GetUserLinks_Call) Run(run func(ctx context.Context, limit int32, offset int32)) *MockILinksService_GetUserLinks_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int32
		if args[1] != nil {
			arg1 = args[1].(int32)
		}
		var arg2 int32
		if args[2] != nil {
			arg2 = args[2].(int32)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockILinksService_GetUserLinks_Call) Return(strings []string, n int32, err error) *MockILinksService_GetUserLinks_Call {
	_c.Call.Return(strings, n, err)
	return _c
}

func (_c *MockILinksService_GetUserLinks_Call) RunAndReturn(run func(ctx context.Context, limit int32, offset int32) ([]string, int32, error)) *MockILinksService_GetUserLinks_Call {
	_c.Call.Return(run)
	return _c
}
