// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package app

import (
	"context"
)

// Injectors from wireInit.go:

func InitServerApp(ctx context.Context) (*App, func(), error) {
	httpConf, err := ProvideHttpConf()
	if err != nil {
		return nil, nil, err
	}
	grpcConf, err := ProvideGrpcConf()
	if err != nil {
		return nil, nil, err
	}
	natsConf, err := ProvideNatsConf()
	if err != nil {
		return nil, nil, err
	}
	pgConf, err := ProvidePgConf()
	if err != nil {
		return nil, nil, err
	}
	pool, err := ProvidePgPool(ctx, pgConf)
	if err != nil {
		return nil, nil, err
	}
	iAnalyticsRepo := ProvideAnalyticsRepo(ctx, pool)
	iAnalyticsService := ProvideAnalyticsService(iAnalyticsRepo)
	analyticsServiceServer := ProvideAnalyticsHandler(iAnalyticsService)
	iConsumer := ProvideNatsConsumer(natsConf)
	app := &App{
		HttpConf:         httpConf,
		GrpcConf:         grpcConf,
		NatsConf:         natsConf,
		AnalyticsHandler: analyticsServiceServer,
		AnalyticsService: iAnalyticsService,
		AnalyticsRepo:    iAnalyticsRepo,
		NatsConsumer:     iConsumer,
	}
	return app, func() {
	}, nil
}
