syntax = "proto3";

package links;

import "google/protobuf/empty.proto";
import "google/api/annotations.proto";
import "google/protobuf/timestamp.proto";

option go_package = "url_shortener/shared/gen/links;links";

service LinksService {
    rpc CreateLink (CreateLinkRequest) returns (CreateLinkResponse){
        option (google.api.http) = {
            post: "/links"
            body: "*"
        };
    }

    rpc GetOriginalLink (GetOriginalLinkRequest) returns (GetOriginalLinkResponse){
        option (google.api.http) = {
            get: "/links/{short_link}"
        };
    }

    rpc GetUserLinks (GetUserLinksRequest) returns (GetUserLinksResponse){
        option (google.api.http) = {
            get: "/links"
        };
    }

    rpc GetLinkInfo (GetLinkInfoRequest) returns (LinkInfo){
        option (google.api.http) = {
            get: "/links/info/{short_link}"
        };
    }

    rpc DeleteLink (DeleteLinkRequest) returns (google.protobuf.Empty){
        option (google.api.http) = {
            delete: "/links/{short_link}"
        };
    }

}

message CreateLinkRequest {
    string original_link = 1;
}

message CreateLinkResponse {
    string short_link = 1;
}

message GetOriginalLinkRequest {
    string short_link = 1;
}

message GetOriginalLinkResponse {
    string original_url = 1;
}

message GetUserLinksRequest {
    int32 limit = 1;
    int32 offset = 2;
}

message GetUserLinksResponse {
    repeated string links = 1;
    int32 total_count = 2;
}

message GetLinkInfoRequest {
    string short_link = 1;
}

message LinkInfo {
    string id = 1;
    string user_id = 2;
    string short_link = 3;
    string original_link_host = 4;
    string original_link = 5;
    google.protobuf.Timestamp created_at = 6;
}

message DeleteLinkRequest {
    string short_link = 1;
}
