name: tests

on:
  push:
    branches:
      - main

jobs:
  go-tests:
    name: Go tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.work
          cache-dependency-path: |
            services/auth/go.sum
            services/links/go.sum
            shared/go.sum

      - name: Install protoc
        run: sudo apt-get update && sudo apt-get install -y protobuf-compiler

      - name: Create env
        run: |
          cat > .env <<'EOF'
          GRPC_HOST=0.0.0.0
          GRPC_AUTH_PORT=8080
          GRPC_LINKS_PORT=8081
          GRPC_AUTH_DOCKER_HOST=url_shortener_auth

          HTTP_HOST=0.0.0.0
          HTTP_AUTH_PORT=8083
          HTTP_LINKS_PORT=8084

          PG_NAME=user
          PG_USER=user
          PG_PASSWORD=pass
          PG_AUTH_DSN=host=127.0.0.1 user=user password=pass dbname=user port=5432 sslmode=disable
          PG_LINKS_DSN=host=127.0.0.1 user=user password=pass dbname=user port=5432 sslmode=disable

          REDIS_HOST=127.0.0.1
          REDIS_PORT=6379
          REDIS_PASSWORD=red_pass
          REDIS_DB=0
          REDIS_TTL_MINUTES=600

          AUTH_MIGRATION_DIR=./services/auth/migrations
          LINKS_MIGRATION_DIR=./services/links/migrations

          JWT_SECRET_KEY=test_secret_key
          JWT_ACCESS_EXPIRY_MINUTES=60
          EOF

      - name: Install generators
        run: make install-all

      - name: Fetch google annotations
        run: make get-annotation

      - name: Generate proto code
        run: make generate-services

      - name: Generate mocks
        run: make generate-mocks

      - name: Run tests
        run: |
          go clean -testcache
          go test ./services/auth/...
          go test ./services/links/...
          go test ./shared/...
